app:
  name: "authly"
  version: "0.2"

server:
  host: "0.0.0.0"
  port: 8000

auth:
  keys_path: "keys"
  active_kid: "main"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "authly"
  sslmode: "disable"

logging:
  level: "info"

