app:
  name: "authly"

server:
  host: "0.0.0.0"
  port: 8000

auth:
  keys_path: "/etc/authly/keys"
  active_kid: "key_id"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "authly"
  sslmode: "disable"

logging:
  level: "info"

